# Generated by Django 3.1.7 on 2021-04-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('dev', models.BooleanField(default=True)),
                ('freq', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='property.category')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='property.stage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
