# Generated by Django 3.1.7 on 2021-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='website',
            managers=[
            ],
        ),
    ]
