# Generated by Django 3.1.7 on 2021-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('server_name', models.CharField(max_length=50)),
                ('server_ip', models.CharField(max_length=50)),
                ('server_id', models.CharField(max_length=100)),
                ('server_password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
